
var dom = document.getElementById("worldmap");
var myChart_map = echarts.init(dom);
var app = {};
option = null;

    option = {
        //backgroundColor:'#ffebd3',
        title: {
            //text: '各国发生航空事故数量统计 (1919.08.11-2019.04.24)',
            subtext: '1919.08.11-2019.04.24',
            sublink: 'https://aviation-safety.net/database',
            left: 'right'
        },
        tooltip: {
            trigger: 'item',
            showDelay: 0,
            transitionDuration: 0.2,
            formatter: function (params) {
                var value = (params.value + '').split('.');
                value = value[0].replace(/(\d{1,3})(?=(?:\d{3})+(?!\d))/g, '$1,');
                return params.seriesName + '<br/>' + params.name + ': ' + value;
            }
        },
        visualMap: {
            left: 'right',
            min: 1,
            max: 1000,
            inRange: {
                color:['#4592af', '#33313b']
                //color:['lightskyblue','#fee090', 'orangered']
                //color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
            },
            text:['High','Low'],           // 文本，默认为数值文本
            calculable: true
        },

        series: [
            {
                name: '事故总数',
                type: 'map',
                roam: true,
                map: 'world',
                zoom:1.2, /*放大*/
                //center: [100, 30], /*中心坐标*/
                itemStyle:{
                    
                    emphasis:{label:{show:true}}
                },
                // 文本位置修正
                textFixed: {
                    Alaska: [20, -20]
                },

                data:[
                    {"name":"United States of America","value":"3993"},
                    {"name":"Russia","value":"1232"},
                    {"name":"Unknown country","value":"868"},
                    {"name":"United Kingdom","value":"796"},
                    {"name":"Canada","value":"730"},
                    {"name":"India","value":"670"},
                    {"name":"Brazil","value":"571"},
                    {"name":"France","value":"534"},
                    {"name":"China","value":"490"},
                    {"name":"Germany","value":"468"},
                    {"name":"Colombia","value":"440"},
                    {"name":"Indonesia","value":"414"},
                    {"name":"Italy","value":"338"},
                    {"name":"Netherlands","value":"330"},
                    {"name":"Myanmar","value":"330"},
                    {"name":"Mexico","value":"315"},
                    {"name":"Vietnam","value":"314"},
                    {"name":"Australia","value":"309"},
                    {"name":"Philippines","value":"293"},
                    {"name":"P.N. Guinea","value":"262"},
                    {"name":"Spain","value":"249"},
                    {"name":"Japan","value":"241"},
                    {"name":"Argentina","value":"231"},
                    {"name":"Cuba","value":"220"},
                    {"name":"Democratic Republic of the Congo","value":"218"},
                    {"name":"Atlantic Ocean","value":"205"},
                    {"name":"Bolivia","value":"203"},
                    {"name":"Venezuela","value":"188"},
                    {"name":"Pacific Ocean","value":"170"},
                    {"name":"Iran","value":"149"},
                    {"name":"Ukraine","value":"149"},
                    {"name":"Peru","value":"135"},
                    {"name":"Nigeria","value":"133"},
                    {"name":"Turkey","value":"132"},
                    {"name":"Egypt","value":"126"},
                    {"name":"Afghanistan","value":"123"},
                    {"name":"Angola","value":"122"},
                    {"name":"Norway","value":"118"},
                    {"name":"Greece","value":"114"},
                    {"name":"Belgium","value":"113"},
                    {"name":"Poland","value":"110"},
                    {"name":"Pakistan","value":"109"},
                    {"name":"South Africa","value":"109"},
                    {"name":"Taiwan","value":"106"},
                    {"name":"Sudan","value":"101"},
                    {"name":"Puerto Rico","value":"99"},
                    {"name":"Laos","value":"97"},
                    {"name":"Ecuador","value":"96"},
                    {"name":"Libya","value":"96"},
                    {"name":"Thailand","value":"94"},
                    {"name":"Algeria","value":"93"},
                    {"name":"Kenya","value":"90"},
                    {"name":"Malaysia","value":"84"},
                    {"name":"South Korea","value":"82"},
                    {"name":"Chile","value":"81"},
                    {"name":"Morocco","value":"79"},
                    {"name":"Kazakhstan","value":"78"},
                    {"name":"South Sudan","value":"77"},
                    {"name":"Antarctica","value":"74"},
                    {"name":"Switzerland","value":"73"},
                    {"name":"Bangladesh","value":"68"},
                    {"name":"Romania","value":"68"},
                    {"name":"Yemen","value":"66"},
                    {"name":"Nepal","value":"66"},
                    {"name":"Bahamas","value":"65"},
                    {"name":"Ethiopia","value":"64"},
                    {"name":"Portugal","value":"63"},
                    {"name":"Panama","value":"63"},
                    {"name":"Sweden","value":"63"},
                    {"name":"Iraq","value":"61"},
                    {"name":"Lebanon","value":"59"},
                    {"name":"Guatemala","value":"57"},
                    {"name":"Ireland","value":"57"},
                    {"name":"Denmark","value":"53"},
                    {"name":"Saudi Arabia","value":"52"},
                    {"name":"Czech Rep.","value":"51"},
                    {"name":"Honduras","value":"51"},
                    {"name":"United Republic of Tanzania","value":"49"},
                    {"name":"New Zealand","value":"48"},
                    {"name":"Costa Rica","value":"47"},
                    {"name":"Iceland","value":"46"},
                    {"name":"Austria","value":"45"},
                    {"name":"Cambodia","value":"45"},
                    {"name":"Greenland","value":"45"},
                    {"name":"Nicaragua","value":"44"},
                    {"name":"Uzbekistan","value":"43"},
                    {"name":"Israel","value":"43"},
                    {"name":"Hong Kong","value":"43"},
                    {"name":"Hungary","value":"43"},
                    {"name":"Bulgaria","value":"42"},
                    {"name":"Dominican Rep.","value":"42"},
                    {"name":"Mozambique","value":"38"},
                    {"name":"Georgia","value":"37"},
                    {"name":"Somalia","value":"36"},
                    {"name":"Mediterranean Sea","value":"35"},
                    {"name":"Finland","value":"34"},
                    {"name":"Sri Lanka","value":"33"},
                    {"name":"Guyana","value":"32"},
                    {"name":"Syria","value":"32"},
                    {"name":"Malta","value":"32"},
                    {"name":"U.A.E.","value":"32"},
                    {"name":"Belarus","value":"30"},
                    {"name":"Singapore","value":"29"},
                    {"name":"Croatia","value":"28"},
                    {"name":"Cameroon","value":"28"},
                    {"name":"Haiti","value":"26"},
                    {"name":"Armenia","value":"25"},
                    {"name":"Cyprus","value":"25"},
                    {"name":"Chad","value":"24"},
                    {"name":"Solomon Isl.","value":"23"},
                    {"name":"Zimbabwe","value":"23"},
                    {"name":"Republic of Congo","value":"23"},
                    {"name":"Liberia","value":"23"},
                    {"name":"Kyrgyzstan","value":"23"},
                    {"name":"Vanuatu","value":"23"},
                    {"name":"Gabon","value":"22"},
                    {"name":"Azerbaijan","value":"22"},
                    {"name":"U.S. Virgin Isl.","value":"22"},
                    {"name":"Jamaica","value":"22"},
                    {"name":"Serbia","value":"22"},
                    {"name":"Indian Ocean","value":"21"},
                    {"name":"Tunisia","value":"21"},
                    {"name":"Maldives","value":"21"},
                    {"name":"Guam","value":"21"},
                    {"name":"Eritrea","value":"20"},
                    {"name":"Ghana","value":"20"},
                    {"name":"Belize","value":"20"},
                    {"name":"Turkmenistan","value":"20"},
                    {"name":"Jordan","value":"20"},
                    {"name":"El Salvador","value":"20"},
                    {"name":"Senegal","value":"19"},
                    {"name":"Fiji","value":"19"},
                    {"name":"Uruguay","value":"19"},
                    {"name":"Zambia","value":"19"},
                    {"name":"Oman","value":"19"},
                    {"name":"Mali","value":"18"},
                    {"name":"Uganda","value":"18"},
                    {"name":"Slovakia","value":"18"},
                    {"name":"Paraguay","value":"18"},
                    {"name":"Djibouti","value":"18"},
                    {"name":"Mongolia","value":"18"},
                    {"name":"Suriname","value":"17"},
                    {"name":"Estonia","value":"16"},
                    {"name":"Tajikistan","value":"16"},
                    {"name":"Madagascar","value":"15"},
                    {"name":"Cote d'Ivoire","value":"15"},
                    {"name":"Niger","value":"14"},
                    {"name":"North Korea","value":"14"},
                    {"name":"C.A.R.","value":"13"},
                    {"name":"French Polynesia","value":"13"},
                    {"name":"Mauritania","value":"13"},
                    {"name":"Botswana","value":"13"},
                    {"name":"Turks &amp; Caicos","value":"12"},
                    {"name":"Namibia","value":"11"},
                    {"name":"U.S. M.O. Islands","value":"11"},
                    {"name":"Kuwait","value":"11"},
                    {"name":"Marshall Isl.","value":"11"},
                    {"name":"Micronesia","value":"11"},
                    {"name":"Latvia","value":"11"},
                    {"name":"Lithuania","value":"11"},
                    {"name":"Guadeloupe","value":"11"},
                    {"name":"Bermuda","value":"11"},
                    {"name":"Trinidad & Tobago","value":"11"},
                    {"name":"Gambia","value":"10"},
                    {"name":"Bosnia","value":"10"},
                    {"name":"North Macedonia","value":"10"},
                    {"name":"Bahrain","value":"9"},
                    {"name":"Saint Lucia","value":"9"},
                    {"name":"Sierra Leone","value":"9"},
                    {"name":"North Pole","value":"9"},
                    {"name":"Falkland Isl.","value":"9"},
                    {"name":"Gibraltar","value":"8"},
                    {"name":"Republic of Equatorial Guinea","value":"8"},
                    {"name":"Luxembourg","value":"8"},
                    {"name":"Papua New Guinea","value":"8"},
                    {"name":"Malawi","value":"8"},
                    {"name":"New Caledonia","value":"7"},
                    {"name":"Moldova","value":"7"},
                    {"name":"Comoros","value":"7"},
                    {"name":"Benin","value":"6"},
                    {"name":"Rwanda","value":"6"},
                    {"name":"Albania","value":"6"},
                    {"name":"Cura?ao","value":"6"},
                    {"name":"Qatar","value":"6"},
                    {"name":"American Samoa","value":"6"},
                    {"name":"Western Sahara","value":"6"},
                    {"name":"Sao Tome","value":"6"},
                    {"name":"Slovenia","value":"6"},
                    {"name":"Burkina Faso","value":"5"},
                    {"name":"Kiribati","value":"5"},
                    {"name":"Samoa","value":"5"},
                    {"name":"St. Helena","value":"5"},
                    {"name":"St. Vincent","value":"5"},
                    {"name":"Bhutan","value":"4"},
                    {"name":"Martinique","value":"4"},
                    {"name":"Palau","value":"4"},
                    {"name":"Northern Mariana Isl","value":"4"},
                    {"name":"B.V.I.","value":"4"},
                    {"name":"Antigua","value":"4"},
                    {"name":"Togo","value":"4"},
                    {"name":"Aruba","value":"4"},
                    {"name":"Montenegro","value":"4"},
                    {"name":"Lesotho","value":"4"},
                    {"name":"St. Kitts &amp; Nevis","value":"3"},
                    {"name":"Norfolk Island","value":"3"},
                    {"name":"Dominican Republic","value":"3"},
                    {"name":"Sint Maarten","value":"3"},
                    {"name":"Montserrat","value":"3"},
                    {"name":"Cape Verde","value":"3"},
                    {"name":"Seychelles","value":"2"},
                    {"name":"Barbados","value":"2"},
                    {"name":"Anguilla","value":"2"},
                    {"name":"Trinidad &amp; Tobago","value":"2"},
                    {"name":"St.Pierre &amp; Miquelon","value":"2"},
                    {"name":"Cocos Isl.","value":"2"},
                    {"name":"Caribbean Neth'lands","value":"2"},
                    {"name":"Cayman Isl.","value":"2"},
                    {"name":"Timor","value":"1"},
                    {"name":"Grenada","value":"1"},
                    {"name":"Tuvalu","value":"1"},
                    {"name":"French Guiana","value":"1"},
                    {"name":"Mauritius","value":"1"},
                    {"name":"Burundi","value":"1"},
                    {"name":"Reunion","value":"1"},
                    {"name":"Monaco","value":"1"},
                    {"name":"Macau","value":"1"},
                    {"name":"Cook Isl.","value":"1"},
                    {"name":"Tonga","value":"1"},
                    {"name":"Kosovo","value":"1"},
                    {"name":"Guinea","value":"1"},
                    {"name":"Christmas Isl.","value":"1"},
                    {"name":"Eswatini","value":"1"},

                ]
            }
        ]
    };
    myChart_map.setOption(option);
